[package]
name = "slowdorust"
version = "0.1.0"
authors = ["mjvl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.0"
scoped_threadpool = "0.1.*"
clap = "3.0.0-beta.5"